version: "3"

interval: 500ms

env:
  DIR: "cd ${PWD} &&"

  MARKFILE: markdown.md
  PDF: converted.pdf
  HTML: converted.html

  PDF_ENGINE: weasyprint

  TITLE: "Cam Scott - Full Stack Engineer"
tasks:
  docker-build:
    cmds:
      - "{{.DIR}} docker build --tag docker.io/library/pandoc --file src/pandoc.dockerfile ."

  pandoc:exec:
    vars:
      TYPE: "html"
    cmd: echo {{.TYPE}}

  pandoc:html:
    deps: [build]
    cmds:
      - |
        {{.DIR}} docker run \
        --rm \
        -v ${PWD}/bin:/workspace \
        -w /workspace \
        docker.io/library/pandoc \
        --pdf-engine=weasyprint \
        -f markdown -c style.css \
        --metadata 'title={{.TITLE}}' \
        {{.MARKFILE}} -t html5 -o {{.HTML}} --embed-resources --standalone

  sass:
    cmd: "{{.DIR}} sass src/style.scss bin/style.css"

  markdown:
    cmd: "{{.DIR}} cp src/{{.MARKFILE}} bin/{{.MARKFILE}}"

  # convert:html:
  #   cmd: "{{.DIR}} pandoc -f markdown -t html5 -o bin/{{.HTML}} bin/{{.MARKFILE}} -c bin/style.css"

  # convert:pdf:
  #   cmd: "{{.DIR}} pandoc -f markdown -t pdf -o bin/{{.PDF}} bin/{{.MARKFILE}} -c bin/style.css"
  #   # cmd: "{{.DIR}} pandoc"
  
  build:
    deps: [sass, markdown, docker-build]
    
  open:pdf:
    cmds:
      - cmd: "{{.DIR}} open bin/{{.OUTNAME}}.pdf"

  dev:
    watch: true
    cmds:
      - task: convert

  run:
    cmds:
      - task: pandoc:html
