version: "3"

interval: 500ms

env:
  DIR: "cd ${PWD} &&"

  MARKFILE: markdown.md
tasks:
  docker-build:
    cmds:
      - "{{.DIR}} docker build --tag docker.io/library/pandoc --file src/pandoc.dockerfile ."

  pandoc:exec:
    cmds:
      - |
        {{.DIR}} docker run \
        --rm \
        -v ${PWD}/bin:/workspace \
        -w /workspace \
        docker.io/library/pandoc \
        --pdf-engine=weasyprint \
        -f markdown -c style.css \
        --metadata 'title={{.TITLE}}' \
        {{.MARKFILE}} -t {{.TYPE}} -o {{.OUTFILE}} --embed-resources --standalone

  pandoc:pdf:
    cmds:
      - task: pandoc:exec
        vars: 
          TYPE: pdf
          OUTFILE: pdf_doc.pdf
        
  pandoc:html:
    cmds:
      - task: pandoc:exec
        vars: 
          TYPE: html5
          OUTFILE: html_doc.html

  sass:
    cmd: "{{.DIR}} sass src/style.scss bin/style.css"

  markdown:
    cmd: "{{.DIR}} cp src/{{.MARKFILE}} bin/{{.MARKFILE}}"

  build:
    deps: [sass, markdown, docker-build]

  dev:
    watch: true
    cmds:
      - task: sass
      - task: markdown
      - task: pandoc:html
      - task: pandoc:pdf
    sources:
      - src/**

  run:
    cmds:
      - task: pandoc:html
