version: "3"

interval: 500ms

env:
  DIR: "cd ${PWD} &&"

  MARKFILE: markdown-content.md
tasks:
  docker-build:
    cmds:
      - "{{.DIR}} docker build --tag docker.io/library/pandoc --file src/pandoc.dockerfile ."

  pandoc:exec:
    cmds:
      - |
        {{.DIR}} docker run \
        --rm \
        -v ${PWD}/bin:/workspace \
        -w /workspace \
        docker.io/library/pandoc \
        --pdf-engine=weasyprint \
        -f markdown -c style.css \
        --metadata 'title={{.TITLE}}' \
        {{.MARKFILE}} -t {{.TYPE}} -o {{.OUTFILE}} --embed-resources --standalone

  pandoc:pdf:
    cmds:
      - task: pandoc:exec
        vars: 
          TYPE: pdf
          OUTFILE: pdf_doc.pdf
        
  pandoc:html:
    cmds:
      - task: pandoc:exec
        vars: 
          TYPE: html5
          OUTFILE: html_doc.html

  transform:ts-to-json:
    cmds:
      - cmd: "npx tsx src/typescript/ts-to-json.ts"
  transform:json-to-markdown:
    cmds:
      - cmd: "npx tsx src/typescript/ts-to-json.ts"
  # transform:markdown-to-pdf:
  # transform:markdown-to-html:

  run:
    cmds:
      - task: docker-build
      - task: sass
      - task: transform:ts-to-json
      - task: transform:json-to-markdown
      # - task: transform:markdown-to-html
      # - task: transform:markdown-to-pdf

  sass:
    cmd: "{{.DIR}} sass src/style.scss bin/style.css"

  build:
    deps: [sass, markdown, docker-build]

  dev:
    watch: true
    cmds:
      - cmd: deno task to-json
      - cmd: deno task to-markdown
      - task: sass
      - task: pandoc:html
      - task: pandoc:pdf
    sources:
      - "src/**/*"
      - "inputs/**/*"

  # run:
  #   cmds:
  #     - task: pandoc:html
